import type { Metadata } from "next";
import { forbidden, unauthorized } from "next/navigation";
import { getServerSession } from "@/lib/get-session";

export const metadata: Metadata = {
  title: "Admin settings | Posts",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await getServerSession();
  const user = session?.user;

  if (!user) {
    unauthorized();
  }
  if (user?.role !== "admin") {
    forbidden();
  }
  return (
    <div>
      <h3 className="text-lg font-medium">Posts</h3>
      <p className="text-neutral-300 mt-2">
        Manage posts and publishing workflows.
      </p>
    </div>
  );
}
