import { getServerSession } from "@/lib/get-session";
import { Metadata } from "next";
import { forbidden, unauthorized } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin settings | Rubrics",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await getServerSession();
  const user = session?.user;

  if (!user) {
    unauthorized();
  }
  if (user?.role !== "admin") {
    forbidden();
  }

  return (
    <div>
      <h3 className="text-lg font-medium">Rubrics</h3>
      <p className="text-neutral-300 mt-2">Manage rubrics and categories.</p>
    </div>
  );
}
