import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin settings | Rubrics",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-lg font-medium">Rubrics</h3>
      <p className="text-neutral-300 mt-2">Manage rubrics and categories.</p>
    </div>
  );
}
