import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin settings | Moderation",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-lg font-medium">Moderation</h3>
      <p className="text-neutral-300 mt-2">
        Manage reports, comments, and user content moderation.
      </p>
    </div>
  );
}
