import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin settings | Monetization",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-lg font-medium">Monetization</h3>
      <p className="text-neutral-300 mt-2">
        Manage pricing, subscriptions, and payouts.
      </p>
    </div>
  );
}
