// biome-ignore assist/source/organizeImports: <explanation>
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { PresenceProvider } from "@/context/PresenceContext";
import { LoginModal } from "./components/authLayout/LoginModal";
import { ThemeProvider } from "next-themes";
import DevBreakpointBadgeClient from "../components/ui/DevBreakpointBadgeClient";
import { getServerSession } from "@/lib/get-session";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Matrix Tricks",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const userId = session?.user?.id ?? null;
  const initialVisibilityEnabled = session?.user?.onlineVisibility ?? true;

  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.variable} mx-auto antialiased xl:container`}>
        <AuthProvider>
          <PresenceProvider
            userId={userId}
            initialVisibilityEnabled={initialVisibilityEnabled}
          >
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
            </ThemeProvider>
          </PresenceProvider>
          <DevBreakpointBadgeClient />
          <LoginModal />
        </AuthProvider>
      </body>
    </html>
  );
}
