import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin settings | Graphic",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-lg font-medium">Graphic</h3>
      <p className="text-neutral-300 mt-2">
        Manage visual assets and design settings.
      </p>
    </div>
  );
}
