import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin settings | E-shop",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h3 className="text-lg font-medium">E-shop</h3>
      <p className="text-neutral-300 mt-2">Manage products and orders.</p>
    </div>
  );
}
